### ISSUE TITLE
Do we really want to go there?

### ISSUE THREAD

**Issue by maximelefrancois86** [w3c-lbd-cg/geometry#1]
How about just dropping this repo?

- a 3D model described using this ontology will be very verbose and heavy
- no tool supports this ontology yet
- tens of 3D geometry formats are supported by hundreds of tools
- converters exist from IFC to some of these formats
- some building element vendors can expose the 3D model of the elements in their catalogue

So a very simple Datatype Property could suffice, as proposed in https://github.com/w3c-lbd-cg/bot/issues/37

**Comment by pipauwel** [comment]
LDAC2018: yes, it would be good to drop this repository, yet move it to a separate community group that focuses on geometry itself (incl. input from geospatial domain working groups and so on).

In addition, the BOT ontology is enriched with two properties (hasSimpleGeometry and hasComplexGeometry) that can be used for initial examples and tests with geometry.

**Comment by maximelefrancois86** [comment]
Perfect

**Comment by pipauwel** [comment]
created repository at: https://github.com/w3c-geom-cg/geom

Closing this one.
